# Generated by Django 2.2.5 on 2020-06-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20200627_2140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomtype',
            options={'verbose_name': 'Room Type'},
        ),
        migrations.RenameField(
            model_name='room',
            old_name='check_int',
            new_name='check_in',
        ),
        migrations.AlterField(
            model_name='room',
            name='address',
            field=models.CharField(max_length=140),
        ),
    ]
